### ISSUE TITLE
rootfs with extra deps already xcompiled

### ISSUE THREAD

**Issue by LanderU** [asobhy-qnx/ros2#1]
Hey @asobhy-qnx,

thanks for this! I'm wondering if it's possible(I can do it if you provide some instruction), to have as part of the build script the possibility to download the rootfs where the third party dependencies are already xcompiled. This could reduce the complexity of the project. You've menthioned this on: https://github.com/ros2/ros2/issues/988#issue-664723776

Let me know your opinion.

Thanks in advance!

**Comment by asobhy-qnx** [comment]
Hi Lander,

I will be providing instructions on how to cross-compile the dependencies. I have not gotten to it just yet but hopefully will start working on it soon.

**Comment by LanderU** [comment]
> I will be providing instructions on how to cross-compile the dependencies. I have not gotten to it just yet but hopefully will start working on it soon.

Cool, let me know if I can help you with something.

**Comment by asobhy-qnx** [comment]
@LanderU if you would like to get a head start in cross compiling ROS2 for QNX you can take a look at the doc I created here https://github.com/asobhy-qnx/ros2_documentation/blob/master/source/Installation/Rolling/QNX-Development-Setup.rst. Please note that the location of the repos here is temporary and we will be moving them to a more official spot soon.

**Comment by LanderU** [comment]
@asobhy-qnx, thanks a lot! I'll try to follow the instructions and let you know what's the result. Thanks again!
